#pragma once

#include <array>

// Directly calibrated (not fit) per-Time subBassGain, feeding AuraFDNEngine::setSubBassGain() -
// the in-loop, 120Hz-pivot attenuation added to address the sub-bass decay-RATE limit documented
// on AuraFDNEngine.h's inputHighPassL (that filter, being outside the feedback loop, can only fix
// LEVEL - see its own KNOWN LIMIT comment). Third attempt at this problem; the first two (uniform
// and asymmetric line-count increases) were rejected - see numLines' comment and git history
// around 2026-09-02 for the full story of why an in-loop gain, not a topology change, was the
// approach that actually worked. Hand-authored - NOT regenerated by any ml-toolkit script, same
// convention as AuraDecayGainData.h/AuraOnsetTiltData.h.
//
// Calibration method: for each Time setting, holding AuraDecayGainData.h's own decayGain/
// dampingWeight FIXED (a direct side-effect check found adding this shelf shifts them by <0.5dB
// in level and doesn't move hi-mid/high bands or crest factor at all - see below - so the
// existing table didn't need re-deriving), binary-searched subBassGain so the render's own
// low(20-120Hz)-vs-mid(120-500Hz) full_decay_rt60 GAP matches the REAL reference capture's own
// gap at that Time setting - NOT simply zero. The reference's own gap is small and inconsistent
// in sign at most settings (+5.9% at Time=0.5s, -4.6% at Time=1.8s, -0.1% at Time=4.5s) but a
// genuine outlier at Time=0.1s (-31.5%, the real hardware's OWN low band decays much FASTER than
// its mid band there) - this table chases that real shape, not an assumption of flatness.
//
// Time=0.1s could not fully reach its target within a reasonable range: the achievable gap
// asymptotes around -0.08s well short of the real -0.152s target (tried down to subBassGain=0.05,
// which bought almost nothing over 0.3 - both land within 0.01s of each other) - 0.3 was kept
// over the search's own more extreme floor since it gets the same practical benefit with
// meaningfully less aggressive per-lap attenuation. Every other point converged within ~0.005s.
//
// Side-effect check (Time=0.1s and Time=5.5s, spanning the calibrated range): hi-mid (500-2000Hz)
// and high (2000-8000Hz) bands' decay time and level are unchanged to within measurement noise at
// every subBassGain value tried, including the most aggressive (0.3 at Time=0.1s). Crest factor
// is bit-for-bit unchanged even at that most aggressive setting (28.35dB -> 28.38dB at Time=0.1s,
// 20.70dB unchanged at Time=5.5s) - unlike the two rejected line-count attempts, this mechanism
// does not touch the reverb's density/transient character at all. Low-band level does shift more
// at short Time (-4 to -6dB at the more aggressive settings) than at long Time (<0.5dB) - expected
// (short Time needs much stronger attenuation to hit its own, much larger, real target gap) and
// plausibly a further improvement given the low band was already independently measured running
// too bright (see AuraDecayGainData.h) - confirm via the full 65-capture validate.py, not assumed.
//
// Values below are calibrated against the CURRENT 8-line topology. Re-run if that topology, OR
// AuraDecayGainData.h's own decayGain/dampingWeight table, ever change.
namespace AuraSubBassGainData
{
    struct TimeToSubBassGainPoint
    {
        float timeSeconds;
        float subBassGain;
    };

    // Sorted ascending by timeSeconds.
    static constexpr std::array<TimeToSubBassGainPoint, 8> timeToSubBassGain { {
        { 0.1f, 0.30000f },
        { 0.5f, 0.76250f },
        { 1.1f, 0.96289f },
        { 1.8f, 0.94805f },
        { 2.3f, 0.98887f },
        { 3.0f, 0.99443f },
        { 4.5f, 0.99629f },
        { 5.5f, 0.99629f },
    } };
}
