#pragma once

#include <array>

// Directly measured (not fit) onset spectral tilt (10*log10(HF/LF energy), 2kHz split, first
// 20ms after onset) at each captured High setting, Low=0. Hand-authored - NOT regenerated by any
// ml-toolkit script, unlike AuraReferenceData.h - keep it that way; a script overwriting this
// file would silently wipe hand-verified measurements the same way re-running
// plugins/intruder-gated-reverb/analysis/validate.py once wiped its own hand-curated "Status" section.
//
// Why this table exists (Phase D finding, 2026-09-02): AuraFDNEngine's feedbackShelf (driven by
// the automated Python fit's high_band_gain/low_band_gain) only touches the signal after at least
// one feedback round trip - it produced ZERO measurable difference in onset tilt between High=0
// and High=-8 on a real render (both measured 9.906dB, identical to 3 decimal places). The real
// hardware's onset tilt is present from the very first energy in the signal (same finding
// Intruder's H made on this same physical unit - see IntruderReferenceData.h's hToOnsetTiltDb).
// This table drives a proper input-stage TiltFilter (AuraFDNEngine::setInputTilt(),
// AuraParameterMap::mapInputTiltDb()) instead, mirroring IntruderParameterMap's exact recipe.
//
// Values are the mean over 5 Time settings (0.5, 1.8, 1.1, 2.3, 3.0s) at each High, all Low=0 -
// tight agreement across Time (std well under 0.05dB at every High) confirms this is a real,
// Time-independent hardware characteristic, not measurement noise. Time=0.1s was excluded: its
// very different envelope shape (see findings.md's "Time" section - isolated early bounces before
// a dense wash, not a smooth decay) makes a fixed 20ms onset window an unreliable measurement
// there specifically, not because the underlying tilt behaves differently.
namespace AuraOnsetTiltData
{
    struct HighToOnsetTiltPoint
    {
        float highDb;
        float onsetTiltDb; // 10*log10(HF/LF energy) in the first 20ms, mean across 5 Time settings.
    };

    // Sorted ascending by highDb - AuraParameterMap's interpolation assumes this ordering.
    static constexpr std::array<HighToOnsetTiltPoint, 3> highToOnsetTiltDb { {
        { -8.0f, 1.4341f },
        { -4.0f, 4.8416f },
        { 0.0f, 9.4155f },
    } };
    static_assert(highToOnsetTiltDb.back().highDb == 0.0f,
        "AuraParameterMap::mapInputTiltDb() treats the last point as the High=0 neutral reference");
}
