#pragma once

// AUTO-GENERATED by ml-toolkit/core/export.py (2026-09-01) - do not hand-edit.
// Regenerate via effects/aura/export_params.py. Single source of truth for
// aura's fitted-parameter reference points - if these are ever re-measured or
// re-fit, update the captures/fit config and regenerate, not this file directly.
//
// Provenance:
//   git commit:         cef0f3cd464c9295d4da56e9df0bbc636d212087
//   capture set hash:   3b214d8cbe252c96
//   fit config hash:    fcd14c4928400438
//   fit date:           2026-09-02
//   ml-toolkit version: 0.1.0

#include <array>

namespace wildjag::dsp
{

struct FittedPoint { float x; float y; };

// time_to_high_band_gain
static constexpr std::array<FittedPoint, 8> time_to_high_band_gainPoints { {
    { 0.1f, 0.5957640409469604f },
    { 0.5f, 0.6772400736808777f },
    { 1.1f, 0.76027512550354f },
    { 1.8f, 0.8923478722572327f },
    { 2.3f, 0.898818850517273f },
    { 3.0f, 0.9413469433784485f },
    { 4.5f, 0.9630979299545288f },
    { 5.5f, 0.9733275175094604f },
} };
static_assert(time_to_high_band_gainPoints.front().x <= time_to_high_band_gainPoints.back().x,
    "time_to_high_band_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_high_band_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_high_band_gain_offsetPoints { {
    { -8.0f, -0.012981712818145752f },
    { -4.0f, 0.020137369632720947f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_high_band_gain_offsetPoints.front().x <= high_to_high_band_gain_offsetPoints.back().x,
    "high_to_high_band_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_low_band_gain
static constexpr std::array<FittedPoint, 8> time_to_low_band_gainPoints { {
    { 0.1f, 0.27037644386291504f },
    { 0.5f, 0.5229633450508118f },
    { 1.1f, 0.6618789434432983f },
    { 1.8f, 0.7909846901893616f },
    { 2.3f, 0.8415744304656982f },
    { 3.0f, 0.878388524055481f },
    { 4.5f, 0.9016841053962708f },
    { 5.5f, 0.9214968085289001f },
} };
static_assert(time_to_low_band_gainPoints.front().x <= time_to_low_band_gainPoints.back().x,
    "time_to_low_band_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_low_band_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_low_band_gain_offsetPoints { {
    { -8.0f, 0.002755582332611084f },
    { -4.0f, -0.0024423599243164062f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_low_band_gain_offsetPoints.front().x <= high_to_low_band_gain_offsetPoints.back().x,
    "high_to_low_band_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_damping_weight_mean
static constexpr std::array<FittedPoint, 8> time_to_damping_weight_meanPoints { {
    { 0.1f, 0.4650573134422302f },
    { 0.5f, 0.7350902557373047f },
    { 1.1f, 0.8517171740531921f },
    { 1.8f, 0.8687797784805298f },
    { 2.3f, 0.9788245558738708f },
    { 3.0f, 0.9795111417770386f },
    { 4.5f, 0.9819992780685425f },
    { 5.5f, 0.9834132194519043f },
} };
static_assert(time_to_damping_weight_meanPoints.front().x <= time_to_damping_weight_meanPoints.back().x,
    "time_to_damping_weight_meanPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_damping_weight_mean_offset
static constexpr std::array<FittedPoint, 3> high_to_damping_weight_mean_offsetPoints { {
    { -8.0f, -0.11235231161117554f },
    { -4.0f, -0.05612760782241821f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_damping_weight_mean_offsetPoints.front().x <= high_to_damping_weight_mean_offsetPoints.back().x,
    "high_to_damping_weight_mean_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

} // namespace wildjag::dsp
