#pragma once

// AUTO-GENERATED by ml-toolkit/core/export.py (2026-09-16) - do not hand-edit.
// Regenerate via effects/nonlin/export_params.py. Single source of truth for
// nonlin's fitted-parameter reference points - if these are ever re-measured or
// re-fit, update the captures/fit config and regenerate, not this file directly.
//
// Provenance:
//   git commit:         4cf4e034801c699a5632a82fd73c4ccadc61f138
//   capture set hash:   3802e6e0ad0b96de
//   fit config hash:    60a6e3a299ef08b5
//   fit date:           2026-09-17
//   ml-toolkit version: 0.1.0

#include <array>

namespace wildjag::dsp
{

struct FittedPoint { float x; float y; };

// time_to_t_knee_ms
static constexpr std::array<FittedPoint, 6> time_to_t_knee_msPoints { {
    { 0.1f, 125.102f },
    { 0.8f, 127.143f },
    { 2.2f, 137.12f },
    { 4.8f, 204.875f },
    { 7.0f, 238.889f },
    { 9.8f, 271.48133333333334f },
} };
static_assert(time_to_t_knee_msPoints.front().x <= time_to_t_knee_msPoints.back().x,
    "time_to_t_knee_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_a_ms
static constexpr std::array<FittedPoint, 6> time_to_tau_a_msPoints { {
    { 0.1f, 13.283059642876045f },
    { 0.8f, 14.941309366474432f },
    { 2.2f, 14.941309366474432f },
    { 4.8f, 16.489063273115747f },
    { 7.0f, 23.047314997214798f },
    { 9.8f, 24.398451347211918f },
} };
static_assert(time_to_tau_a_msPoints.front().x <= time_to_tau_a_msPoints.back().x,
    "time_to_tau_a_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_fall_rate_db_per_s
static constexpr std::array<FittedPoint, 6> time_to_fall_rate_db_per_sPoints { {
    { 0.1f, -151.11f },
    { 0.8f, -143.1f },
    { 2.2f, -141.05f },
    { 4.8f, -148.29f },
    { 7.0f, -177.69f },
    { 9.8f, -179.55666666666664f },
} };
static_assert(time_to_fall_rate_db_per_sPoints.front().x <= time_to_fall_rate_db_per_sPoints.back().x,
    "time_to_fall_rate_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_k_ms
static constexpr std::array<FittedPoint, 6> time_to_tau_k_msPoints { {
    { 0.1f, 0.6691259145736694f },
    { 0.8f, 0.3866204023361206f },
    { 2.2f, 0.6921746134757996f },
    { 4.8f, 29.764934539794922f },
    { 7.0f, 4.533920884132385f },
    { 9.8f, 2.4752639134724936f },
} };
static_assert(time_to_tau_k_msPoints.front().x <= time_to_tau_k_msPoints.back().x,
    "time_to_tau_k_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_feedback_gain
static constexpr std::array<FittedPoint, 6> time_to_feedback_gainPoints { {
    { 0.1f, 0.9485952854156494f },
    { 0.8f, 0.948706865310669f },
    { 2.2f, 0.9476547241210938f },
    { 4.8f, 0.9025763273239136f },
    { 7.0f, 0.947564423084259f },
    { 9.8f, 0.947330892086029f },
} };
static_assert(time_to_feedback_gainPoints.front().x <= time_to_feedback_gainPoints.back().x,
    "time_to_feedback_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_damping_weight_mean
static constexpr std::array<FittedPoint, 6> time_to_damping_weight_meanPoints { {
    { 0.1f, 0.746536374092102f },
    { 0.8f, 0.7334905862808228f },
    { 2.2f, 0.8294105529785156f },
    { 4.8f, 0.8682268857955933f },
    { 7.0f, 0.8864913582801819f },
    { 9.8f, 0.8854131102561951f },
} };
static_assert(time_to_damping_weight_meanPoints.front().x <= time_to_damping_weight_meanPoints.back().x,
    "time_to_damping_weight_meanPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_diffuser_gain
static constexpr std::array<FittedPoint, 6> time_to_diffuser_gainPoints { {
    { 0.1f, 0.24501697719097137f },
    { 0.8f, 0.2507514953613281f },
    { 2.2f, 0.262243390083313f },
    { 4.8f, 0.22596129775047302f },
    { 7.0f, 0.27080777287483215f },
    { 9.8f, 0.25937453409036f },
} };
static_assert(time_to_diffuser_gainPoints.front().x <= time_to_diffuser_gainPoints.back().x,
    "time_to_diffuser_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_plateau_droop_db_per_s
static constexpr std::array<FittedPoint, 6> time_to_plateau_droop_db_per_sPoints { {
    { 0.1f, -175.555f },
    { 0.8f, -175.517f },
    { 2.2f, -51.612f },
    { 4.8f, -37.255f },
    { 7.0f, -28.433500000000002f },
    { 9.8f, -33.00366666666667f },
} };
static_assert(time_to_plateau_droop_db_per_sPoints.front().x <= time_to_plateau_droop_db_per_sPoints.back().x,
    "time_to_plateau_droop_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_low_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_low_gain_offsetPoints { {
    { -9.0f, 1.481746372405031f },
    { -4.0f, 0.4292329094050229f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_low_gain_offsetPoints.front().x <= high_to_tilt_low_gain_offsetPoints.back().x,
    "high_to_tilt_low_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_high_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_high_gain_offsetPoints { {
    { -9.0f, -0.8532347375050937f },
    { -4.0f, -0.5294992531650122f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_high_gain_offsetPoints.front().x <= high_to_tilt_high_gain_offsetPoints.back().x,
    "high_to_tilt_high_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_plateau_droop_db_per_s_offset
static constexpr std::array<FittedPoint, 3> high_to_plateau_droop_db_per_s_offsetPoints { {
    { -9.0f, 0.382293701171875f },
    { -4.0f, -2.980316162109375f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_plateau_droop_db_per_s_offsetPoints.front().x <= high_to_plateau_droop_db_per_s_offsetPoints.back().x,
    "high_to_plateau_droop_db_per_s_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_t_knee_ms_offset
static constexpr std::array<FittedPoint, 3> high_to_t_knee_ms_offsetPoints { {
    { -9.0f, 87.79999999999998f },
    { -4.0f, 87.79999999999998f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_t_knee_ms_offsetPoints.front().x <= high_to_t_knee_ms_offsetPoints.back().x,
    "high_to_t_knee_ms_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

} // namespace wildjag::dsp
