#pragma once

// AUTO-GENERATED by ml-toolkit/core/export.py (2026-09-16) - do not hand-edit.
// Regenerate via effects/nonlin/export_params.py. Single source of truth for
// nonlin's fitted-parameter reference points - if these are ever re-measured or
// re-fit, update the captures/fit config and regenerate, not this file directly.
//
// Provenance:
//   git commit:         520040de8503a92ce1074167fa1f73fc505cf2bb
//   capture set hash:   3802e6e0ad0b96de
//   fit config hash:    60a6e3a299ef08b5
//   fit date:           2026-09-16
//   ml-toolkit version: 0.1.0

#include <array>

namespace wildjag::dsp
{

struct FittedPoint { float x; float y; };

// time_to_t_knee_ms
static constexpr std::array<FittedPoint, 6> time_to_t_knee_msPoints { {
    { 0.1f, 125.102f },
    { 0.8f, 127.143f },
    { 2.2f, 137.12f },
    { 4.8f, 204.875f },
    { 7.0f, 238.889f },
    { 9.8f, 271.48133333333334f },
} };
static_assert(time_to_t_knee_msPoints.front().x <= time_to_t_knee_msPoints.back().x,
    "time_to_t_knee_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_a_ms
static constexpr std::array<FittedPoint, 6> time_to_tau_a_msPoints { {
    { 0.1f, 13.283059642876045f },
    { 0.8f, 14.941309366474432f },
    { 2.2f, 14.941309366474432f },
    { 4.8f, 16.489063273115747f },
    { 7.0f, 23.047314997214798f },
    { 9.8f, 24.398451347211918f },
} };
static_assert(time_to_tau_a_msPoints.front().x <= time_to_tau_a_msPoints.back().x,
    "time_to_tau_a_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_fall_rate_db_per_s
static constexpr std::array<FittedPoint, 6> time_to_fall_rate_db_per_sPoints { {
    { 0.1f, -151.11f },
    { 0.8f, -143.1f },
    { 2.2f, -141.05f },
    { 4.8f, -148.29f },
    { 7.0f, -177.69f },
    { 9.8f, -179.55666666666664f },
} };
static_assert(time_to_fall_rate_db_per_sPoints.front().x <= time_to_fall_rate_db_per_sPoints.back().x,
    "time_to_fall_rate_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_k_ms
static constexpr std::array<FittedPoint, 4> time_to_tau_k_msPoints { {
    { 2.2f, 1.3292268514633179f },
    { 4.8f, 2.3301613330841064f },
    { 7.0f, 1.0611255168914795f },
    { 9.8f, 0.733187735080719f },
} };
static_assert(time_to_tau_k_msPoints.front().x <= time_to_tau_k_msPoints.back().x,
    "time_to_tau_k_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_feedback_gain
static constexpr std::array<FittedPoint, 4> time_to_feedback_gainPoints { {
    { 2.2f, 0.834037184715271f },
    { 4.8f, 0.9084318280220032f },
    { 7.0f, 0.8920376896858215f },
    { 9.8f, 0.8931784629821777f },
} };
static_assert(time_to_feedback_gainPoints.front().x <= time_to_feedback_gainPoints.back().x,
    "time_to_feedback_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_damping_weight_mean
static constexpr std::array<FittedPoint, 4> time_to_damping_weight_meanPoints { {
    { 2.2f, 0.8367305994033813f },
    { 4.8f, 0.8341593742370605f },
    { 7.0f, 0.9624649882316589f },
    { 9.8f, 0.9672797918319702f },
} };
static_assert(time_to_damping_weight_meanPoints.front().x <= time_to_damping_weight_meanPoints.back().x,
    "time_to_damping_weight_meanPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_plateau_droop_db_per_s
static constexpr std::array<FittedPoint, 6> time_to_plateau_droop_db_per_sPoints { {
    { 0.1f, -175.555f },
    { 0.8f, -175.517f },
    { 2.2f, -51.612f },
    { 4.8f, -37.255f },
    { 7.0f, -28.433500000000002f },
    { 9.8f, -33.00366666666667f },
} };
static_assert(time_to_plateau_droop_db_per_sPoints.front().x <= time_to_plateau_droop_db_per_sPoints.back().x,
    "time_to_plateau_droop_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_low_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_low_gain_offsetPoints { {
    { -9.0f, 0.6771558911531295f },
    { -4.0f, 0.2842793598100224f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_low_gain_offsetPoints.front().x <= high_to_tilt_low_gain_offsetPoints.back().x,
    "high_to_tilt_low_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_high_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_high_gain_offsetPoints { {
    { -9.0f, -0.6636015854521116f },
    { -4.0f, -0.4715363909375674f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_high_gain_offsetPoints.front().x <= high_to_tilt_high_gain_offsetPoints.back().x,
    "high_to_tilt_high_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_pivot_hz_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_pivot_hz_offsetPoints { {
    { -9.0f, -94.98828125f },
    { -4.0f, 248.96728515625f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_pivot_hz_offsetPoints.front().x <= high_to_tilt_pivot_hz_offsetPoints.back().x,
    "high_to_tilt_pivot_hz_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_plateau_droop_db_per_s_offset
static constexpr std::array<FittedPoint, 3> high_to_plateau_droop_db_per_s_offsetPoints { {
    { -9.0f, -4.57720947265625f },
    { -4.0f, -5.2156982421875f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_plateau_droop_db_per_s_offsetPoints.front().x <= high_to_plateau_droop_db_per_s_offsetPoints.back().x,
    "high_to_plateau_droop_db_per_s_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

} // namespace wildjag::dsp
