#pragma once

#include <array>

// Directly calibrated (not fit) shared feedback gain AND per-line damping weight that together
// reproduce each setting's REAL measured decay time and REAL measured overall tonal balance
// (full_decay_rt60_s and the full-tail HF/LF energy ratio, both from
// ml-toolkit/effects/ambience/features.json / direct re-measurement), found via binary search
// against AuraFDNEngine itself. Hand-authored - NOT regenerated by any ml-toolkit script, same
// convention as AuraOnsetTiltData.h - keep it that way.
//
// Why this table exists (Phase D findings, 2026-09-02) - two separate problems with the
// automated Python fit's values in AuraReferenceData.h, found in sequence:
//
// 1. high_band_gain/low_band_gain looked reasonable in isolation (e.g. at Time=5.5s: 0.973 vs
//    0.921, only ~5% apart) but translate into a WILDLY exaggerated decay-time split once
//    actually rendered - measured low-band RT60=4.56s vs high-band RT60=8.99s, nearly 2x, at a
//    setting where the real hardware's own low/high RT60 are within 1.3% of each other (directly
//    measured via band-pass-filtered decay fits on the real captures). RT60 grows roughly like
//    1/(1-gain) near unity, so a "small" fitted gain difference the optimizer's loss didn't
//    penalize strongly enough produces an enormous, clearly audible decay-time mismatch. Fixed by
//    replacing the two independent band gains with ONE shared decayGain per Time+High setting,
//    binary-searched to reproduce each setting's own real overall RT60 (AuraFDNEngine::
//    setBandGains() is still called with the same value for both arguments - a genuine, small,
//    well-measured low/high split could be added back later, this table just replaces the
//    automated fit's unreliable one).
//
// 2. Fixing (1) exposed a second, cleaner problem: dampingWeight was fit systematically too LOW
//    (too much per-line HF filtering) especially at short Time - re-validating after fix (1)
//    showed a smooth, monotonic low-band excess from +9.7dB at Time=0.1s down to +2dB at
//    Time=5.5s, while the real hardware's own full-tail HF/LF ratio is nearly CONSTANT across
//    every Time setting (9.16-9.50dB, directly measured). dampingWeight below is binary-searched
//    (holding decayGain from the table below fixed) to reproduce that flat target ratio at each
//    Time setting - values come out substantially higher (less filtering) than the automated fit
//    found, especially at short Time (0.797 vs the fit's 0.465 at Time=0.1s).
//
// Only calibrated for the Time-only (Low=0, High=0) baseline - no High-offset for dampingWeight
// yet (AuraParameterMap still applies AuraReferenceData.h's own high_to_damping_weight_mean_offset
// curve on top, which was NOT found to have the same problem in isolation, only in combination
// with the two issues above - revisit if further validation shows it needs recalibrating too).
//
// 3. Fixing (1) and (2) initially made the AGGREGATE low-band error WORSE (+3.11 -> +5.02dB),
//    which was itself informative: the old low_band_gain's artificially-fast bass decay had been
//    partially CANCELLING a third, separate problem in the whole-tail average. With the
//    cancellation gone, the real cause was findable - the engine had NO low-frequency rolloff at
//    all while the real unit clearly does (see AuraFDNEngine.h's inputHighPassL comment for the
//    measurement). Adding that input high-pass took the low band from +5.02dB to +1.96dB and the
//    log-spectral distance to 2.49dB, the best of any configuration tried.
//
// Lesson worth keeping: at no point did the aggregate metric alone identify the right fix - it got
// worse while the DSP got more correct, then improved once the actual missing mechanism was found.
// Every real cause here (the RT60 disparity, the flat tonal target, the missing rolloff) came from
// measuring a specific property of the reference captures and comparing it against the same
// property of a render, never from optimising the summary number.
//
// Values below are calibrated against the CURRENT 8-line topology (a 16-line variant was tried and
// rejected - see AuraFDNEngine.h's numLines comment). Re-run the calibration if topology changes.
namespace AuraDecayGainData
{
    struct TimeToDecayGainPoint
    {
        float timeSeconds;
        float decayGain;
        float dampingWeight;
    };

    // Sorted ascending by timeSeconds. Jointly calibrated (alternating gain<-RT60,
    // damping<-tonal-balance searches until both converge) against the 16-line topology - every
    // point lands within 0.003s of its real measured RT60 and 0.04dB of its real measured
    // full-tail HF/LF ratio. RE-RUN THIS CALIBRATION if the topology in AuraFDNEngine.h changes.
    static constexpr std::array<TimeToDecayGainPoint, 8> timeToDecayGain { {
        { 0.1f, 0.52808f, 0.72630f },
        { 0.5f, 0.56014f, 0.84478f },
        { 1.1f, 0.67904f, 0.88210f },
        { 1.8f, 0.81513f, 0.93557f },
        { 2.3f, 0.87742f, 0.96175f },
        { 3.0f, 0.91531f, 0.97500f },
        { 4.5f, 0.93321f, 0.98254f },
        { 5.5f, 0.94538f, 0.98602f },
    } };

    struct HighToDecayGainOffsetPoint
    {
        float highDb;
        float decayGainOffset;
    };

    // Calibrated at Time=2.3s (the only Time setting with a High sweep - same limitation as
    // AuraReferenceData.h's own high_to_*_offset curves). Sorted ascending by highDb.
    static constexpr std::array<HighToDecayGainOffsetPoint, 3> highToDecayGainOffset { {
        { -8.0f, -0.02401f },
        { -4.0f, -0.01730f },
        { 0.0f, 0.0f },
    } };
}
