#pragma once

#include <array>

// Directly calibrated (not fit) shared feedback gain AND per-line damping weight that together
// reproduce each setting's REAL measured decay time and REAL measured overall tonal balance
// (full_decay_rt60_s and the full-tail HF/LF energy ratio, both from
// ml-toolkit/effects/ambience/features.json / direct re-measurement), found via binary search
// against AuraFDNEngine itself. Hand-authored - NOT regenerated by any ml-toolkit script, same
// convention as AuraOnsetTiltData.h - keep it that way.
//
// Why this table exists (Phase D findings, 2026-09-02) - two separate problems with the
// automated Python fit's values in AuraReferenceData.h, found in sequence:
//
// 1. high_band_gain/low_band_gain looked reasonable in isolation (e.g. at Time=5.5s: 0.973 vs
//    0.921, only ~5% apart) but translate into a WILDLY exaggerated decay-time split once
//    actually rendered - measured low-band RT60=4.56s vs high-band RT60=8.99s, nearly 2x, at a
//    setting where the real hardware's own low/high RT60 are within 1.3% of each other (directly
//    measured via band-pass-filtered decay fits on the real captures). RT60 grows roughly like
//    1/(1-gain) near unity, so a "small" fitted gain difference the optimizer's loss didn't
//    penalize strongly enough produces an enormous, clearly audible decay-time mismatch. Fixed by
//    replacing the two independent band gains with ONE shared decayGain per Time+High setting,
//    binary-searched to reproduce each setting's own real overall RT60 (AuraFDNEngine::
//    setBandGains() is still called with the same value for both arguments - a genuine, small,
//    well-measured low/high split could be added back later, this table just replaces the
//    automated fit's unreliable one).
//
// 2. Fixing (1) exposed a second, cleaner problem: dampingWeight was fit systematically too LOW
//    (too much per-line HF filtering) especially at short Time - re-validating after fix (1)
//    showed a smooth, monotonic low-band excess from +9.7dB at Time=0.1s down to +2dB at
//    Time=5.5s, while the real hardware's own full-tail HF/LF ratio is nearly CONSTANT across
//    every Time setting (9.16-9.50dB, directly measured). dampingWeight below is binary-searched
//    (holding decayGain from the table below fixed) to reproduce that flat target ratio at each
//    Time setting - values come out substantially higher (less filtering) than the automated fit
//    found, especially at short Time (0.797 vs the fit's 0.465 at Time=0.1s).
//
// Only calibrated for the Time-only (Low=0, High=0) baseline - no High-offset for dampingWeight
// yet (AuraParameterMap still applies AuraReferenceData.h's own high_to_damping_weight_mean_offset
// curve on top, which was NOT found to have the same problem in isolation, only in combination
// with the two issues above - revisit if further validation shows it needs recalibrating too).
//
// IMPORTANT - fixing (1) and (2) made the full validate.py run's AGGREGATE low-band error worse
// (+3.11dB -> +5.02dB average), not better, even though both fixes are individually correct and
// verified (the RT60 disparity and the flat-ratio target are both directly measured facts, not
// assumptions). Digging into why: the old low_band_gain was making bass decay away artificially
// fast, which happened to partially CANCEL a separate, still-unresolved low-frequency excess in
// the aggregate (full-decay-averaged) comparison - fast-decaying-away bass contributes less to a
// whole-tail average even while genuinely present near onset. Fixing the disparity removed that
// accidental cancellation and made the real remaining problem visible instead of masked: a
// genuine bass excess, worst at short Time (+8.8dB at Time=0.1s even after this fix), that
// decayGain/dampingWeight tuning alone doesn't fully explain. Likely candidate: the fixed
// delay-line/Hadamard topology itself may build up more low-frequency energy than the real
// hardware does, independent of the feedback/damping coefficients - would need topology-level
// investigation (line lengths, mixing matrix) to confirm, not attempted yet. Keep this fix (it's
// correct and the RT60 disparity was severe/audible on its own) but don't mistake the aggregate
// metric alone for "better" or "worse" without checking what's actually driving it, per this note.
namespace AuraDecayGainData
{
    struct TimeToDecayGainPoint
    {
        float timeSeconds;
        float decayGain;
        float dampingWeight;
    };

    // Sorted ascending by timeSeconds.
    static constexpr std::array<TimeToDecayGainPoint, 8> timeToDecayGain { {
        { 0.1f, 0.54197f, 0.79743f },
        { 0.5f, 0.56995f, 0.89111f },
        { 1.1f, 0.68067f, 0.91090f },
        { 1.8f, 0.81666f, 0.94991f },
        { 2.3f, 0.87390f, 0.96924f },
        { 3.0f, 0.91426f, 0.98037f },
        { 4.5f, 0.93324f, 0.98682f },
        { 5.5f, 0.94578f, 0.98957f },
    } };

    struct HighToDecayGainOffsetPoint
    {
        float highDb;
        float decayGainOffset;
    };

    // Calibrated at Time=2.3s (the only Time setting with a High sweep - same limitation as
    // AuraReferenceData.h's own high_to_*_offset curves). Sorted ascending by highDb.
    static constexpr std::array<HighToDecayGainOffsetPoint, 3> highToDecayGainOffset { {
        { -8.0f, -0.01379f },
        { -4.0f, -0.00875f },
        { 0.0f, 0.0f },
    } };
}
