#pragma once

// Phase 4-equivalent mapping layer for Aura (AMS RMX16 "Ambience" emulation): converts UI-facing
// Time/High values into DSP-ready feedback-loop coefficients, using the fitted reference curves
// in AuraReferenceData.h (generated by ml-toolkit/effects/ambience/export_params.py) rather than
// an assumed/guessed relationship. Deliberately no JUCE or AuraFDNEngine dependency - kept
// separate so the mapping can be refit (regenerate AuraReferenceData.h, no engine changes needed)
// without touching the DSP, same convention as IntruderParameterMap.
//
// Time and High are combined ADDITIVELY: value = timeCurve(time) + highOffsetCurve(high) - i.e.
// High's effect is treated as a Time-independent offset from the Time curve's own High=0
// baseline. Only one Time setting (2.3s) had a High sweep in the capture set, so this
// Time-independence assumption is unconfirmed at other Time settings - see
// ml-toolkit/effects/ambience/build_curves.py's "combination_model" note.
namespace AuraParameterMap
{
    struct BandGains
    {
        float highBandGain;
        float lowBandGain;
        float dampingWeight;
    };

    // extrapolated, if non-null, is set true if EITHER timeSeconds or highDb fell outside its own
    // measured range (0.1-5.5s for Time, -8..0dB for High).
    BandGains mapTimeAndHighToBandGains(float timeSeconds, float highDb, bool* extrapolated = nullptr);

    // Low (-8..+6 on the real hardware) is NOT wired to anything below yet - deliberately, not an
    // oversight. The one place the capture grid lets its effect be isolated (Low=+5 vs Low=0,
    // High=-8 fixed, across all 8 Time settings) shows a delta that's negative at short Time
    // settings and only turns positive at longer ones (-0.021 to +0.025 on low_band_gain, no
    // clean sign pattern) - not something that can be hardcoded into a formula without presenting
    // false precision. The parameter still exists on the plugin (matching the real hardware's
    // control set, and so presets/automation referencing it don't need to change later) - it just
    // has no measured effect to apply yet. Needs either more targeted captures (Low swept at
    // several High values) or by-ear tuning, the same way Intruder's automated fit still needed a
    // hand-tuned tankSustainMultiplier sweep afterward.
}
