#pragma once

// AUTO-GENERATED by ml-toolkit/core/export.py (2026-09-17) - do not hand-edit.
// Regenerate via effects/nonlin/export_params.py. Single source of truth for
// nonlin's fitted-parameter reference points - if these are ever re-measured or
// re-fit, update the captures/fit config and regenerate, not this file directly.
//
// Provenance:
//   git commit:         43d2059b8319ba736ee5c81e997fe5273077b630
//   capture set hash:   3802e6e0ad0b96de
//   fit config hash:    60a6e3a299ef08b5
//   fit date:           2026-09-18
//   ml-toolkit version: 0.1.0

#include <array>

namespace wildjag::dsp
{

struct FittedPoint { float x; float y; };

// time_to_t_knee_ms
static constexpr std::array<FittedPoint, 6> time_to_t_knee_msPoints { {
    { 0.1f, 59.25200000000001f },
    { 0.8f, 61.293000000000006f },
    { 2.2f, 137.12f },
    { 4.8f, 199.93200000000002f },
    { 7.0f, 199.93200000000002f },
    { 9.8f, 212.948f },
} };
static_assert(time_to_t_knee_msPoints.front().x <= time_to_t_knee_msPoints.back().x,
    "time_to_t_knee_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_a_ms
static constexpr std::array<FittedPoint, 6> time_to_tau_a_msPoints { {
    { 0.1f, 13.283059642876045f },
    { 0.8f, 14.941309366474432f },
    { 2.2f, 14.941309366474432f },
    { 4.8f, 16.489063273115747f },
    { 7.0f, 23.047314997214798f },
    { 9.8f, 24.398451347211918f },
} };
static_assert(time_to_tau_a_msPoints.front().x <= time_to_tau_a_msPoints.back().x,
    "time_to_tau_a_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_fall_rate_db_per_s
static constexpr std::array<FittedPoint, 6> time_to_fall_rate_db_per_sPoints { {
    { 0.1f, -15.713128205128186f },
    { 0.8f, -36.85797435897433f },
    { 2.2f, -79.14766666666665f },
    { 4.8f, -135.814f },
    { 7.0f, -177.713f },
    { 9.8f, -170.18f },
} };
static_assert(time_to_fall_rate_db_per_sPoints.front().x <= time_to_fall_rate_db_per_sPoints.back().x,
    "time_to_fall_rate_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_tau_k_ms
static constexpr std::array<FittedPoint, 6> time_to_tau_k_msPoints { {
    { 0.1f, 0.7838802933692932f },
    { 0.8f, 0.45271360874176025f },
    { 2.2f, 3.9668707847595215f },
    { 4.8f, 29.716176986694336f },
    { 7.0f, 1.5522608160972595f },
    { 9.8f, 1.774828314781189f },
} };
static_assert(time_to_tau_k_msPoints.front().x <= time_to_tau_k_msPoints.back().x,
    "time_to_tau_k_msPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_feedback_gain
static constexpr std::array<FittedPoint, 6> time_to_feedback_gainPoints { {
    { 0.1f, 0.9488055109977722f },
    { 0.8f, 0.9488700032234192f },
    { 2.2f, 0.9310675859451294f },
    { 4.8f, 0.9439131617546082f },
    { 7.0f, 0.9462866485118866f },
    { 9.8f, 0.9459753433863322f },
} };
static_assert(time_to_feedback_gainPoints.front().x <= time_to_feedback_gainPoints.back().x,
    "time_to_feedback_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_damping_weight_mean
static constexpr std::array<FittedPoint, 6> time_to_damping_weight_meanPoints { {
    { 0.1f, 0.8478138446807861f },
    { 0.8f, 0.8211125135421753f },
    { 2.2f, 0.8458993434906006f },
    { 4.8f, 0.8736988306045532f },
    { 7.0f, 0.8848611116409302f },
    { 9.8f, 0.885959525903066f },
} };
static_assert(time_to_damping_weight_meanPoints.front().x <= time_to_damping_weight_meanPoints.back().x,
    "time_to_damping_weight_meanPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_diffuser_gain
static constexpr std::array<FittedPoint, 6> time_to_diffuser_gainPoints { {
    { 0.1f, 0.23160885274410248f },
    { 0.8f, 0.23505981266498566f },
    { 2.2f, 0.30376893281936646f },
    { 4.8f, 0.3088827431201935f },
    { 7.0f, 0.30799177289009094f },
    { 9.8f, 0.3084732989470164f },
} };
static_assert(time_to_diffuser_gainPoints.front().x <= time_to_diffuser_gainPoints.back().x,
    "time_to_diffuser_gainPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_plateau_droop_db_per_s
static constexpr std::array<FittedPoint, 4> time_to_plateau_droop_db_per_sPoints { {
    { 2.2f, -62.214f },
    { 4.8f, 16.323999999999998f },
    { 7.0f, 32.812999999999995f },
    { 9.8f, 28.198f },
} };
static_assert(time_to_plateau_droop_db_per_sPoints.front().x <= time_to_plateau_droop_db_per_sPoints.back().x,
    "time_to_plateau_droop_db_per_sPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_low_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_low_gain_offsetPoints { {
    { -9.0f, 1.481746372405031f },
    { -4.0f, 0.4292329094050229f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_low_gain_offsetPoints.front().x <= high_to_tilt_low_gain_offsetPoints.back().x,
    "high_to_tilt_low_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_tilt_high_gain_offset
static constexpr std::array<FittedPoint, 3> high_to_tilt_high_gain_offsetPoints { {
    { -9.0f, -0.8532347375050937f },
    { -4.0f, -0.5294992531650122f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_tilt_high_gain_offsetPoints.front().x <= high_to_tilt_high_gain_offsetPoints.back().x,
    "high_to_tilt_high_gain_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_plateau_droop_db_per_s_offset
static constexpr std::array<FittedPoint, 3> high_to_plateau_droop_db_per_s_offsetPoints { {
    { -9.0f, -33.332f },
    { -4.0f, -34.752f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_plateau_droop_db_per_s_offsetPoints.front().x <= high_to_plateau_droop_db_per_s_offsetPoints.back().x,
    "high_to_plateau_droop_db_per_s_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_t_knee_ms_offset
static constexpr std::array<FittedPoint, 3> high_to_t_knee_ms_offsetPoints { {
    { -9.0f, 87.79999999999998f },
    { -4.0f, 87.79999999999998f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_t_knee_ms_offsetPoints.front().x <= high_to_t_knee_ms_offsetPoints.back().x,
    "high_to_t_knee_ms_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_fall_rate_db_per_s_offset
static constexpr std::array<FittedPoint, 3> high_to_fall_rate_db_per_s_offsetPoints { {
    { -9.0f, 18.052f },
    { -4.0f, 27.301999999999985f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_fall_rate_db_per_s_offsetPoints.front().x <= high_to_fall_rate_db_per_s_offsetPoints.back().x,
    "high_to_fall_rate_db_per_s_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// time_to_early_excess_db
static constexpr std::array<FittedPoint, 6> time_to_early_excess_dbPoints { {
    { 0.1f, -5.98375f },
    { 0.8f, -6.62075f },
    { 2.2f, -3.1350000000000002f },
    { 4.8f, -3.8870000000000005f },
    { 7.0f, 0.7110000000000001f },
    { 9.8f, 0.8810000000000002f },
} };
static_assert(time_to_early_excess_dbPoints.front().x <= time_to_early_excess_dbPoints.back().x,
    "time_to_early_excess_dbPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

// high_to_early_excess_db_offset
static constexpr std::array<FittedPoint, 3> high_to_early_excess_db_offsetPoints { {
    { -9.0f, -3.077f },
    { -4.0f, -4.027f },
    { 0.0f, 0.0f },
} };
static_assert(high_to_early_excess_db_offsetPoints.front().x <= high_to_early_excess_db_offsetPoints.back().x,
    "high_to_early_excess_db_offsetPoints must be sorted ascending by x - FittedCurve1D assumes this ordering");

} // namespace wildjag::dsp
